### PR TITLE
Remove most uses of import *

### PR DESCRIPTION
**Pull request by tbekolay**
We keep having an issue with new versions of Java/Jython in which `import *` no longer imports everything we think it does. This should future-proof us, but not relying on `import *`.

### CODE REVIEW

**Comment by tbekolay** [comment]
I'm too lazy to build this locally, so I'm going to merge so that Jenkins builds this so I can test it ¯\_(ツ)_/¯

**Comment by tbekolay** [comment]
FYI this breaks something, which is annoying. I deleted to build on Jenkins so that no one accidentally downloads / installs that build.

**Comment by drasmuss** [comment]
Related to this, the other problem we keep having is that people download the "stable" version, which is missing some bug fixes (like this one).  Should we push out a final stable Java version before the switch to 2.0?

**Comment by tbekolay** [comment]
Yeah; I also want to switch to the (recently released) Jython 2.7.

**Pull request merged**
